mode: auto

# ä¸»é¢˜è‰²
colors:
  primary: "#6200ee"
  # bg: "#F5F5F5"
  selection_bg: "#8e71c1" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# å›¾ç‰‡èƒŒæ™¯
bg_image:
  enable: true
  url: /img/bg/stars.jpg
  # æš—è‰²æ¨¡å¼èƒŒæ™¯å›¾ç‰‡
  dark: /img/bg/stars2.png
  # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦ å»ºè®®åŸå›¾å¤„ç†
  # blur: 30px 
  opacity: 0.8

# æœç´¢èƒŒæ™¯
search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  # dark_bg_image: 
  # placeholder:

# æ ‡ç­¾ é¢œè‰²
tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: "#21374b"

# åˆ†ç±» é¢œè‰²
categories:
  äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"

# å­—ä½“ éè‡ªå¸¦éœ€ head:css:font å¼•å…¥
font:
  cdn:
    enable: true
    lib:
      - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
  serif:
    family: "'Songti SC', 'Noto Serif SC', STZhongsong, STKaiti, KaiTi, Roboto, serif"
    weight: 900
  sans_serif:
    family: "'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
    weight: 400
  monospace:
    family: "'Source Code Pro', 'Courier New', Courier, Consolas, Monaco, monospace"

# ç‚¹å‡»é¡µé¢çš„çƒŸèŠ±æ•ˆæœ
fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

# éšæœºå¤šè¾¹å½¢èƒŒæ™¯
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

# ScrollReveal é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# Cursor å…‰æ ‡  é»˜è®¤/é“¾æ¥/é€‰æ‹©
cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

# æ»šåŠ¨
smoothScroll: true


##èµ„æºæ ¹ç›®å½• /source/####################################

# headåŠ è½½
head:
  css:
    custom: /css/custom.css
    fonts:
  js:
    base:
    async:
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer:

# æ‰¹é‡å¼•å…¥.styl
#custom:
  # style: source/_data/style/*

# ç½‘ç«™å›¾æ ‡ svg
# favicon: /favicon.ico

# CDN jsdelivråˆ·æ–°éœ€è¦24h
cdn:
  # pre: https://cdn.jsdelivr.net/gh/ASIjacket/asijacket.github.io@latest
  pre: ""
  css:
  js:
    base:
    async:
      # é»˜è®¤å¼•å…¥iconfontå›¾æ ‡
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer:

# é¢„åŠ è½½
preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/hexo-theme-yun.js
prefetch:
  script:
    - /js/sidebar.js
dns_prefetch:
# do more(TCP handshake...) than dns-fetch
preconnect:
  - https://cdn.jsdelivr.net


##ä¾§è¾¹æ ####################################

# èƒŒæ™¯ä¸æ ‡ç­¾
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

# å¤´åƒ
avatar:
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking

# ç¤¾äº¤å›¾æ ‡
social:
  # RSS éœ€å®‰è£… éœ€é…ç½®config.yml
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: Telegram
    link: https://t.me/AIKETI
    icon: icon-telegram-line
    color: "#0088CC"

# å¯¼èˆª
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: 
    path: 
    icon: icon-home-4-line
# æ ‡ç­¾äº‘ï¼ˆè¯äº‘ï¼‰
wordcloud:
  enable: true
  # height: 350

# é¡µé¢é“¾æ¥
pages:
  # - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
  #   url: /links/
  #   icon: icon-genderless-line
  #   color: dodgerblue


##ä¸»é¡µ####################################

# æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: 
    - Kirakira
    - Blog
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å…¬å‘Š
notice:
  enable: false
  content: Thanks.

# è®°å½•å–œæ¬¢çš„å¥³å­©å­ä»¬
girls:
  enable: true

# ç›¸å†Œ 
albums:
  enable: false

# æ ‡ç­¾äº‘
wordcloud:
  enable: true
  height: 350

#éšæœºåœ¨ä¸»é¡µæ˜¾ç¤ºä¸€å¥è¯
say:
  enable: false
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  # ä¸€è¨€api ä¼˜å…ˆçº§é«˜äº é»˜è®¤api
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# é»˜å“€
mourn:
  enable: false
  days:
    - "4-4"

##æ–‡ç« ####################################

#å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8

# ä¿¡æ¯æ˜¾ç¤º
post_meta:
  # ä¿¡æ¯æ˜¾ç¤ºä¸ºæ–‡å­—
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

# ç›®å½•
toc:
  # æ˜¾ç¤ºç¼–å·
  list_number: false
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  # æŠ˜å ç›®å½•
  collapse: false

# ä»“åº“è·³è½¬ç¼–è¾‘å›¾æ ‡
post_edit:
  enable: false
  url: https://github.com/ASIjacket/asijacket.github.io/tree/hexo/source/

# å­—æ•°æ—¶é•¿ç»Ÿè®¡ éœ€å®‰è£…
wordcount:
  enable: true
  count: false
  time: true

# ä»£ç ä¸€é”®å¤åˆ¶æŒ‰é’®
codeblock:
  copy_btn: true

# è®¾ç½®ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  # æ–‡ç« æœ«å°¾æ˜¾ç¤º
  post: true
  language: deed.zh
  # å‰ªè´´æ¿ä¸­è¿½åŠ ç‰ˆæƒä¿¡æ¯
  clipboard: false

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true

# æ‰“èµ
reward:
  enable: false
  icon: icon-hand-coin-line
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: 
      path: 
      color: "#00A3EE"
      icon: icon-alipay-line

# æ–‡ç« typeå®šä¹‰
types:
  link:
    color: blue
    icon: icon-external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: icon-bilibili-line
  douban:
    color: "#007722"
    icon: icon-douban-line
  github:
    color: black
    icon: icon-github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: icon-netease-cloud-music-line
  notion:
    color: black
    icon: icon-notion
  twitter:
    color: "#1da1f2"
    icon: icon-twitter-line
  wechat:
    color: "#1AAD19"
    icon: icon-wechat-2-line
  weibo:
    color: "#E6162D"
    icon: icon-weibo-line
  yuque:
    color: "#25b864"
    icon: icon-yuque
  zhihu:
    color: "#0084FF"
    icon: icon-zhihu-line


##é¡µè„š####################################

footer:
  since: 2020
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
    url: 
    title:
  powered:
    enable: false
  beian:
    enable: false
    icp:
  support:
    enable: false
    title:
    link:
    logo:
    prefix:
    suffix:
  live_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2020-02-01T00:00:00"
  #è‡ªå®šä¹‰æ–‡æœ¬ å¯ä»¥åŒ…å« HTML
  custom_text:


##ä¼˜åŒ–åˆ†æ####################################

# è°·æ­Œåˆ†æ
google_analytics:
  enable: true
  id: G-EHWHX6L2NJ

# è°·æ­Œå¹¿å‘Š
google_adsense:
  enable: false
  client: 

# Google è·Ÿè¸ªä»£ç ç®¡ç†å™¨
google_tagmanager:
  enable: false
  id: 

# ç™¾åº¦æœç´¢èµ„æºå¹³å°
baidu_push: true

# å¼•æ“æœç´¢ 
engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: blog.kirakira.eu

# æœ¬åœ°æœç´¢ éœ€å®‰è£… éœ€å…³é—­å¼•æ“æœç´¢
local_search:
  enable: false

# Algoliaæœç´¢ éœ€å®‰è£…
algolia_search:
  enable: false

# è¯„è®º
comment:
  enable: true
  #tips:
    # - è¦ä¸è¦å’Œæˆ‘è¯´äº›ä»€ä¹ˆï¼Ÿ
  # å€™é€‰è¯„è®ºç³»ç»Ÿ  
  # candidates:
  #   - waline
waline:
  enable: true
  serverURL: https://blog-comment-pi.vercel.app
  # allow visitor comment
  visitor: true
  # display comment count
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  meta:
    - nick
    - mail
  requiredMeta: ["nick"]
  recordIP: false
  highlight: true
  pageSize: 10




