mode: auto

# ä¸»é¢˜è‰²
colors:
  primary: "#6200ee"
  # bg: "#F5F5F5"
  selection_bg: "#8e71c1" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# æ ‡ç­¾ é¢œè‰²
tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: "#21374b"

# åˆ†ç±» é¢œè‰²
categories:
  äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"


##èµ„æºæ ¹ç›®å½• /source/####################################

# headåŠ è½½
head:
  css:
    custom: /css/custom.css
  js:
    base:
    async:
    defer:

# ç½‘ç«™å›¾æ ‡ svg
# favicon: /favicon.ico

# CDN jsdelivråˆ·æ–°éœ€è¦24h
cdn:
  # pre: https://cdn.jsdelivr.net/gh/ASIjacket/asijacket.github.io@latest
  pre: ""
  css:
  js:
    base:
    async:
      # é»˜è®¤å¼•å…¥çš„å›¾æ ‡èµ„æºï¼Œä½¿ç”¨ iconfont
      # iconfont: 
    defer:

# é¢„åŠ è½½
preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/hexo-theme-yun.js
prefetch:
  script:
    - /js/sidebar.js
dns_prefetch:
# do more(TCP handshake...) than dns-fetch
preconnect:
  - https://cdn.jsdelivr.net


##ä¾§è¾¹æ ####################################

# èƒŒæ™¯ä¸æ ‡ç­¾
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

# å¤´åƒ
avatar:
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking

# ç¤¾äº¤å›¾æ ‡
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: Telegram
    link: https://t.me/AIKETI
    icon: icon-telegram-line
    color: "#0088CC"

# å¯¼èˆª
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: icon-settings-line

# é¡µé¢é“¾æ¥
pages:
  # - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
  #   url: /links/
  #   icon: icon-genderless-line
  #   color: dodgerblue


######################################
# ä¸»é¡µ
# æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: 
    - Kirakira
    - Blog
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# å…¬å‘Š
notice:
  enable: false
  content: Thanks.



reward:
  enable: false
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: 

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: ["nick"]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

footer:
  since: 2020
  icon:
    url: 
  beian:
    enable: false
  support:
    enable: false

  custom_text:

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia

  # ...

# google_analytics:
#   enable: true
#   id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: false



pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink



cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  # id: GTM-M9KWR9L


say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false


