mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

reward:
  enable: false
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: 

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: ["nick"]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

footer:
  since: 2020
  icon:
    url: 
  beian:
    enable: false
  support:
    enable: false

  custom_text:

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia

  # ...

# google_analytics:
#   enable: true
#   id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: false

tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: "#21374b"


categories:
  äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  # id: GTM-M9KWR9L


say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

# è´¦å·
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange